---
- name: Install packages
  become: true
  apt:
    update_cache: yes
    state: latest
    pkg:
      - stow
      
- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_git_repository }}"
    dest: "{{ dotfiles_install_path }}"
    update: true
    accept_hostkey: true

- name: stow packages
  shell: "{{ dotfiles_install_path }}/bootstrap.sh {{ dotfiles_package_ids }}"
