- name: Install tmux
  become: true
  apt:
    update_cache: yes
    state: latest
    pkg:
      - tmux

- name: Copy tmux config
  copy:
    src: "files/tmux.conf"
    dest: "~/.tmux.conf"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'