---
- name: Install packages
  become: true
  apt:
    update_cache: yes
    state: latest
    pkg:
      - unattended-upgrades
      - apt-listchanges
      - mailutils

- name: Update config
  become: true
  lineinfile:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { regexp: '^\/\/Unattended-Upgrade::Mail "r.*', line: 'Unattended-Upgrade::Mail "root";', state: present }
    - { regexp: '^\/\/Unattended-Upgrade::Automatic-Reboot ".*', line: 'Unattended-Upgrade::Automatic-Reboot "true";', state: present }
